services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsBlogSystem\:
    resource: '../Classes/*'

  NITSAN\NsBlogSystem\EventListener\BlogViewCounterListener:
    tags:
      - name: event.listener
        identifier: 'blog-view-counter'