services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsBlogSystem\:
    resource: '../Classes/*'

  NITSAN\NsBlogSystem\EventListener\BlogViewCounterListener:
    tags:
      - name: event.listener
        identifier: 'blog-view-counter'
  
  NITSAN\NsBlogSystem\EventListener\CoreRequestListener:
    tags:
      - name: event.listener
        identifier: 'blog-core-request'

  NITSAN\NsBlogSystem\Command\ResetBlogViewsCommand:
    tags:
      - name: 'console.command'
        command: 'nsblog:resetviews'
        description: 'Reset blog views monthly'